# Generated by Django 3.2.6 on 2021-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_form', models.CharField(max_length=30)),
                ('cover_type', models.CharField(max_length=30)),
                ('union_type', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to='')),
                ('sub_cover', models.ImageField(upload_to='')),
                ('have_sub_cover', models.BooleanField(default=False)),
                ('sheets_quantity', models.PositiveIntegerField()),
                ('sheets_type', models.CharField(max_length=20)),
            ],
        ),
    ]
