# Generated by Django 3.2.6 on 2021-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue_margin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
