# Generated by Django 3.2.6 on 2021-08-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Colombia', max_length=100),
            preserve_default=False,
        ),
    ]
